### PR TITLE
due to an upstream change, fetching pip by versioned script

### PR DESCRIPTION
**Pull request by chayim**

### CODE REVIEW

**Comment by rafie** [comment]
This code within `setup.py` is actually supersedes by `getpy2/3` and we should avoid calling `setup_pip()` from any `system-setup.py` script, and finally deprecate `setup_pip()` completely. Which modules are still calling `setup_pip()`?
I prefer finishing the whole python/pip setup thing before we even invoke `system-setup.py` because it involves messing with Python while running it, which already caused weird problems on macOS.

**Comment by chayim** [comment]
A quick grep shows that ModuleBuilders/modules, redsedge, RedisGears, RedisJSON, rejson, and RSCoordinator all use it (based on what's on my filesystem).

**Comment by rafie** [comment]
I think `ModuleBuilders/modules` is a little out-of-date (we really need to update it).
Here's what I've collected:
```
ModuleBuilders/python/system-setup.py
ModuleBuilders/rmbuilder/system-setup.py

RLTest/sbin/system-setup.py

RSCoordinator-1.6/system-setup.py
RSCoordinator-1.8/system-setup.py
RSCoordinator-2.0/system-setup.py

RediSearch-1.6/system-setup.py

RedisAI-1.2/opt/system-setup.py

RedisEdge/pylibs/system-setup.py

RedisGears-1.0/build/cpython/system-setup.py
RedisGears/build/cpython/system-setup.py
RedisGears/system-setup.py

RedisJSON/system-setup.py

rgsync/build/reqpacks/system-setup.py
rgsync/sbin/system-setup.py
```

I suggest we remove it from those modules (some can use `system-setup.py` refactoring anyway), and then remove `setup_pip()`  and similar methods from paella.

**Comment by chayim** [comment]
Let's break this into two distinct tasks. The first is to unblock builds - the second is to handle these cases.  I've created #11 for tracking that item, so that we can merge this in and fix the current issue.

**Comment by rafie** [comment]
Let's close this one, I deprecated `setup_pip`. No module will need it anyway because they're going `getpy` before `system-setup.py`.

**Pull request closed without merging**
